"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FileName = void 0;
var FileName;
(function (FileName) {
    FileName["BUG_REPORT"] = "bug_report.md";
    FileName["FEATURE_REQUEST"] = "feature_request.md";
    FileName["PULL_REQUEST"] = "pull_request_template.md";
    FileName["BUG"] = "Bug.md";
    FileName["CI_TEMPLATE"] = "example-ci.yml";
    FileName["FEATURE_PROPOSAL"] = "Feature proposal.md";
    FileName["MERGE_REQUEST"] = "merge_request_template.md";
    FileName["CODE_OF_CONDUCT"] = "CODE_OF_CONDUCT.md";
    FileName["CONTRIBUTING"] = "CONTRIBUTING.md";
    FileName["LICENSE"] = "LICENSE";
    FileName["README"] = "README.md";
    FileName["TODO"] = "TODO.md";
    FileName["CHANGELOG"] = "CHANGELOG.md";
    FileName["SECURITY"] = "SECURITY.md";
    FileName["APPSPEC"] = "appspec.yml";
    FileName["BUILDSPEC"] = "buildspec.yml";
    FileName["DOCKERFILE"] = "Dockerfile";
})(FileName = exports.FileName || (exports.FileName = {}));
